mitraweb/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('financials/', include('financials.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('register/', include('register.urls')),
    path('admin/', admin.site.urls),
]

register/urls.py
from django.urls import path

from . import views

app_name = 'register'

urlpatterns = [
    path('', views.register, name='register'),
    path('link_plaid/', views.link_plaid, name='link_plaid'),
    path('get_link_token/', views.get_link_token, name='get_link_token'),
    path('get_access_token/', views.get_access_token, name='get_access_token'),
    path('get_access_token_app/', views.get_access_token_app, name='get_access_token_app'),
    path('register_app/', views.register_app, name='register_app')

]

register/models.py
from django.db import models
from django.contrib.auth.models import User

class PlaidKey(models.Model):
    # user = models.ForeignKey(User, on_delete=models.CASCADE)
    # access_token = models.CharField(max_length=200)
    # item_id = models.CharField(max_length=200)

    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)
    access_token = models.CharField(max_length=200)
    item_id = models.CharField(max_length=200)

    def __str__(self):
        return "Access Token: "+self.access_token+" | Item ID: "+self.item_id

register/forms.py
from django import forms

class RegisterForm(forms.Form):
    username = forms.CharField(label='Username', max_length=100)
    email = forms.EmailField(label='Email', max_length=100)
    password = forms.CharField(label='Password', max_length=100)
    conf_password = forms.CharField(label='Repeat Password', max_length=100)

register/views.py
import plaid
import json
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.contrib.auth.models import User
from plaid_config import PlaidConfig
from django.http import JsonResponse
from django.urls import reverse
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login
from django.views.decorators.csrf import csrf_exempt

from .models import PlaidKey

from .forms import RegisterForm

conf = PlaidConfig()

client = plaid.Client(client_id=conf.PLAID_CLIENT_ID,
                      secret=conf.PLAID_SECRET,
                      environment=conf.PLAID_ENV)


@csrf_exempt
def register_app(request):
    params =  json.loads(request.body)
    if request.method != 'POST': print("NOT A POST REQUEST")
    username = params['username']
    password = params['password']
    conf_password = params['conf_password']
    email = params['email']

    if User.objects.filter(username=username).exists():
        print("FAILED: Username already exists")
    
    elif password!=conf_password:
        print("FAILED: Passwords do not match")
    
    else:
        user = User.objects.create_user(username, email, password)
        login(request, user)
        print("SUCCESS: Logged in", username)

        response = {}
        return JsonResponse(response)
    
    response = {}
    return JsonResponse(response)

    



def register(request):
    # if this is a POST request we need to process the form data
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        form = RegisterForm(request.POST)
        # check whether it's valid:
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            conf_password = form.cleaned_data['conf_password']
            email = form.cleaned_data['email']

            # process the data in form.cleaned_data as required
            if User.objects.filter(username=username).exists():
                form = RegisterForm()
                return render(request, 'register/register.html', {'form': form, 'user_err': True, 'pass_err': False})
            
            elif password!=conf_password:
                form = RegisterForm()
                return render(request, 'register/register.html', {'form': form, 'user_err': False, 'pass_err': True})
            
            else:
                user = User.objects.create_user(username, email, password)
                login(request, user)
                
                #redirect to plaid
                return HttpResponseRedirect(reverse('register:link_plaid'))

    # if a GET (or any other method) we'll create a blank form
    else:
        form = RegisterForm()

    return render(request, 'register/register.html', {'form': form, 'user_err': False, 'pass_err': False})

def get_link_token(request):
    print("enter get link")
    
    # Create a link_token for the given user
    response = client.LinkToken.create({
      'user': {
        'client_user_id': request.user.username,
      },
      'products': conf.PLAID_PRODUCTS,
      'client_name': 'My App',
      'country_codes': conf.PLAID_COUNTRY_CODES,
      'language': 'en',
    })

    link_token = response['link_token']

    print('GET_LINK_TOKEN: Success') 
    # Send the data to the client
    return JsonResponse(response)

def link_plaid(request):
    if not request.user.is_authenticated:
        return HttpResponseRedirect('/accounts/login/')
        
    return render(request, 'register/link.html', {})
    
def get_access_token(request):
    print("IN GET ACCESS TOKEN")
    public_token = request.POST['public_token']
    exchange_response = client.Item.public_token.exchange(public_token)

    key = PlaidKey(user=request.user, access_token=exchange_response['access_token'], item_id=exchange_response['item_id'])
    key.save()

    print('access token: ' + exchange_response['access_token'])
    print('item ID: ' + exchange_response['item_id'])

@csrf_exempt
def get_access_token_app(request):
    print("IN GET ACCESS TOKEN APP")

    params = json.loads(request.body)
    public_token = params['public_token']
    exchange_response = client.Item.public_token.exchange(public_token)

    key = PlaidKey(user=request.user, access_token=exchange_response['access_token'], item_id=exchange_response['item_id'])
    key.save()

    print('access token: ' + exchange_response['access_token'])
    print('item ID: ' + exchange_response['item_id'])

    response = {}
    return JsonResponse(response)

register/templates/register/<!DOCTYPE html>.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>Plaid Quickstart Example</title>
    <link rel="stylesheet" href="https://threads.plaid.com/threads.css" />

    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'financials/style.css' %}">
    <meta name="viewport" content="width=device-width, initial-scale=1" />
  </head>

  <body>
    <main class="main">
      <div class="grid">
        
      </div>
    </main>
  </body>
</html>

register/templates/register/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>Mitra</title>
    <link rel="stylesheet" href="https://threads.plaid.com/threads.css" />
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'financials/style.css' %}">
    <meta name="viewport" content="width=device-width, initial-scale=1" />
  </head>
  

  <body>
    <main class="main">
        <div class="grid">
            <div class="grid__column grid__column--is-twelve-columns">
            <div id="banner" class="everpresent-content">
                <h1 class="everpresent-content__heading">Mitra</h1>
                <p id="intro" class="everpresent-content__subheading">
                An example application that outlines an end-to-end integration
                with Plaid
                </p>
                <!-- <p id="steps" class="everpresent-content__subheading">
                Success! You just created an Item by linking your account.
                </p> -->
            <body>
                <div>Links: <a href="/register/">Register</a> <a href="/accounts/login/">Login</a> <a href="/accounts/logout/">Logout</a> <a href="/financials/">Financials</a> </div>
            </body>
        </div>

            {% block content %}{% endblock %}
         </div>
    </div>
  </body>
</html>

register/templates/register/link.html
{% extends "registration/base.html" %}

{% block content %}

<head>
  <title>Connect a bank</title>
</head>
<button id="link-btn">Open Link</button>
<script src="https://cdn.plaid.com/link/v2/stable/link-initialize.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.3/jquery.min.js"></script>
{% csrf_token %}
<script>

var csrftoken = jQuery("[name=csrfmiddlewaretoken]").val();
function csrfSafeMethod(method) {
    // these HTTP methods do not require CSRF protection
    return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
}
$.ajaxSetup({
    beforeSend: function(xhr, settings) {
        if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
            xhr.setRequestHeader("X-CSRFToken", csrftoken);
        }
    }
});

// console.log("Enter link page");
// const linkHandler = Plaid.create({
//   token: await $.post('/get_link_token'),
//   onSuccess: (public_token, metadata) => {
//     // Send the public_token to your app server.
//     $.post('/get_access_token', {
//       public_token: public_token,
//     });
//   },
//   onExit: (err, metadata) => {
//     // Optionally capture when your user exited the Link flow.
//     // Storing this information can be helpful for support.
//   },
//   onEvent: (eventName, metadata) => {
//     // Optionally capture Link flow events, streamed through
//     // this callback as your users connect an Item to Plaid.
//   },
// });

// $("#link-btn").on("click", function (e) {
//     console.log("BUTTON CLICKED")
//     linkHandler.open();
// });

console.log("Enter link page");
$.post("/register/get_link_token/", {}, function (data) {
    localStorage.setItem("link_token", data.link_token);
    handler = Plaid.create({
    token: data.link_token,
    onSuccess: function (public_token) {
        $.post(
        "/register/get_access_token/",
        {
            public_token: public_token
        },
        function (data) {
            console.log("success");
        }
        );
    }
    });
});


$("#link-btn").on("click", function (e) {
    console.log("BUTTON CLICKED")
    handler.open();
});
        
</script>
{% endblock %}

register/templates/register/register.html
{% extends "registration/base.html" %}

{% block content %}

{% if user_err %}
<p>That username already exists. Please try again.</p>
{% endif %}

{% if not user_err and pass_err %}
<p>Passwords did not match. Please try again.</p>
{% endif %}

<form method="post" action="{% url 'register:register' %}">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit">
</form>

{% endblock %}